version: '3'
networks:
  app_network:
    external: true
services:
  app_service:
    image: app_image
    container_name: app_1
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - app_network